language: node_js

node_js:
- "8"

cache:
  directories:
    - node_modules

before_install:
  - npm install -g gatsby-cli

install:
  - npm install

script:
  - gatsby build

# 배포 설정
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  script:
    - npm run deploy
  on:
    branch: master