version: "3.7"

services:
  wordpress:
    container_name: WP__hyeon.pro
    image: wordpress:php7.4
    restart: always
    ports:
      - 32775:80
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - ./.wordpress:/var/www/html
      - ./Theme:/var/www/html/wp-content/themes/hapas
      - ./backup:/var/www/html/wp-content/ai1wm-backups
    external_links:
      - DB__wordpress:mariadb
  
networks:
  default:
    external:
      name: db_net
